// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdewUsdnwFvlma688MIV3nd57oVffzCTA',
    appId: '1:454483449652:web:db2258983e5a524b39b761',
    messagingSenderId: '454483449652',
    projectId: 'my-firebase-project-386a9',
    authDomain: 'my-firebase-project-386a9.firebaseapp.com',
    storageBucket: 'my-firebase-project-386a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdhWqETJeU3QoLT8qR0M8nTMUBzfijuEU',
    appId: '1:454483449652:android:31e871dd863528a239b761',
    messagingSenderId: '454483449652',
    projectId: 'my-firebase-project-386a9',
    storageBucket: 'my-firebase-project-386a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbnl_34V3xFvWkmfRsAs5o1bxy0STcjO4',
    appId: '1:454483449652:ios:3db02194f3ab4d3339b761',
    messagingSenderId: '454483449652',
    projectId: 'my-firebase-project-386a9',
    storageBucket: 'my-firebase-project-386a9.appspot.com',
    iosBundleId: 'com.example.flutterUam',
  );
}
